server	[
	listen	0.0.0.0:8080;
	name	test.com;
	
	location	/	{
		root	html/empty;
		methods GET POST DELETE;
		index	index.html file favicon.ico;
	}

	location	/directory	{
		methods GET;
		index	youpi.bad_extension;
		root	html/YoupiBanane;
	}
]
